### ISSUE TITLE
Background color/image not exported

### ISSUE THREAD

**Issue by dalboris** [dalboris/vpaint#100]
This is a current regression from VPaint 1.6. Since layers have been introduced, background is not exported. See comment in `View::drawToImage()`.

**Comment by ebarranco** [comment]
I recently notice this and the only way that I've could solve it was drawing a shape and fill it with the paint tool then extend it with motion paste for all the animation frames. It's not very elegant but it works for now.

**Comment by dalboris** [comment]
Yes, this trick works for background color, unfortunately not for background images :( This should be fixed in the next few days.

**Comment by ebarranco** [comment]
@dalboris Well it's almost March... I think I Won't sound impatient if I ask about this and the release of vpaint 1.7.

**Comment by dalboris** [comment]
@ebarranco Yes, you absolutely have every right to be impatient! :) I'm doing things in this order: finish account system on vgc.io where sponsors can downloads continuous builds of VGC, then get back to VPaint 1.7. The reason for this order is that I want the account system to be ready when I announce that VPaint 1.7 is released, so that people can register on the new system from VPaint. I prefer not to promise a timeline at this point, although I'm getting impatient too and would like to be done with this as soon as possible and get back to working on VGC ;)

**Comment by ebarranco** [comment]
Aware now, thanks!

**Comment by dalboris** [comment]
This is now fixed, at long last! :)
