### ISSUE TITLE
A default background layer.

### ISSUE THREAD

**Issue by ebarranco** [dalboris/vpaint#102]
Vpaint shows a canvas from start yet, we don't have any layers to draw in. A default background layer is need it or no canvas at all  in the beginning. [I try to explain it better here.](https://www.dropbox.com/s/ipgdrorrugz5zrz/2018-12-06%2022-42-31.mov?dl=0)

**Comment by dalboris** [comment]
Yes, this is in my todo list :) New documents will have a default layer called "Layer 1" with white background color. I hesitated to call it "Background", but I think this could confuse user. And I'll make it clear in the Background Panel that this affects only the current layer.

**Comment by dalboris** [comment]
There you go, it should work now! :) I'm still keeping this open for now to remember to improve the Background Panel a little.

**Comment by ebarranco** [comment]
I have a new behavior with the sketch tool after the changes I'll open a new issue with the details.
