### ISSUE TITLE
Keyframe selection crash vpaint

### ISSUE THREAD

**Issue by ebarranco** [dalboris/vpaint#106]
Vpaint Master.
OS Linux.

Issue:
Using "keyframe selection" on a face with holes result in Vpaint crashing.

Steps:
1. Draw a circle and fill
2. Make a hole
3. Copy/motion paste 
4. Change position
5. select a frame in-between and keyframe the selection (k)
6. Vpaint Crash.

**Comment by dalboris** [comment]
Thanks for the report, I wasn't aware of this one! If it's an easy fix I may be able to squeeze it in VPaint 1.7 :)

**Comment by dalboris** [comment]
Alright, this one is fixed too now! The cause of this crash was a bit tricky to find and understand, but fortunately, the fix was actually easy :) Thanks for the report!
