### ISSUE TITLE
VPaint's download link triggers ad blockers

### ISSUE THREAD

**Issue by wilhelmtell** [dalboris/vpaint#11]
VPaint's download link on vpaint.org refers to SourceForge. I suggest changing that to a different host. Because of the recent issues with SourceForge (manipulating files they host, injecting ads, malware and so on) some ad blockers[0] already block SourceForge downloads with an alarming warning.

What would you think of removing traces of the project from SourceForge and pointing the download link at a GitHub release page instead?

 [0] I see this on uBlock Origin.

**Comment by scribblemaniac** [comment]
This has already been discussed [here](http://vpaint.org/forum/viewtopic.php?f=4&t=56) and it sounds like everything will be off of SourceForge shortly.

**Comment by dalboris** [comment]
Ok, now the download links on vpaint.org point to GitHub instead. :-) I'll take care of deleting vpaint from sourceforge later.
