### ISSUE TITLE
Just hello

### ISSUE THREAD

**Issue by kosirm** [dalboris/vpaint#121]
This is not an issue, just comment.
I can't find any community to say this, please make discord or something.
What I want to say,,, this program is just mind-blowing. Your work is revolutionary!
The world is waiting for this! Please, find some developers, don't do it alone !!!
I've been in software development over 25 years and I've seen so many great projects
collapsing under it's own weight. You are genious, but you need to build community.
Just my best wishes to this project!
BR, Milan

**Comment by kosirm** [comment]
Actually, I got an idea. I was thinking, how good it would be to have **THIS** in blender greasepencil...
And...bam! Idea! Just drop this standalone program (or don't drop it), and **make a blender addon**!
In the same moment you will get all that you need, huge user base, huge ecosystem, community,
many patreon supporters, etc. etc. Just an idea 😄

**Comment by dalboris** [comment]
Hi @kosirm , thank you for you warm comment, I'm glad you like my work! You're the third person now to mention Discord, I'll probably create one soon, it's a good idea. I tried a PHPBB forum before and it didn't get the necessary traction, was buggy (didn't get email notifications in a timely manner), and there were annoying spambots despite many measures taken. A Discord may hopefully work better and more engaging / better spontaneous discussions :)

If possible, a Blender addon would be a wonderful idea! A few thoughts though:

- It's probably more complicated than it seems: the data structure required by VPaint/VGC is very different from the data blobs stored in Blender. It might be possible to work around it, but it's probably complicated, and working with the VGC data structure requires plenty of specific tools in the interface.

- I want a super simple intuitive interface. You open the app, and boom, you start drawing, no documentation required. There's quite a learning curve with Blender, and you lose 90% of people there.

So I'm definitely not dropping the standalone program, it has a lot of advantage over addons (in Blender or other software), such as a custom interface tailored to work with the custom data structure of VGC. But *in addition* to the standalone program, yes, addons may make sense. I definitely understand how existing users of grease pencil would benefit from some of the VGC tech.

Cheers and thanks again for the comments and ideas!

**Comment by kosirm** [comment]
Thank you @dalboris ! I'm honored to get response from THE AUTHOR ! I'm so proud 😄 
Good argument! (This is the latest joke / saying in our family 😄 )
Ok, I agree with you, but look at it from the standpoint of new user (e.g. me). Yes, boom, I can start to draw, but if I want something more, I need to learn new shortcuts, new buttons, etc. So, on the end, learning curve is the same if it is standalone or addon. On the other hand, just do the math. Getting proffesional level timeline, dopesheet, sequencer, realtime renderer, etc. and a huge ecosystem of people interested to integrate your genious math into their workflow vs. try to achieve all this on your own... 
Don't worry, blender users already know how to use blender. And we are talking about millions of users.
Thank you for taking my idea in consideration! Cheers!

**Comment by dalboris** [comment]
@kosirm Yes, obviously current Blender artists would prefer to have this as a Blender add-on :-) There's no question about that, and that's why I said it makes sense *in addition* to the standalone app. But most 2D artists don't use Blender (especially those doing non-animated vector art), and forcing these 2D artists to use Blender if they are interested in VGC isn't so nice for them either. This is why my priority for now is the standalone app, but I may consider a Blender add-on in the future.

**Comment by kosirm** [comment]
God bless you! Your work is excellent! I will use it no matter if it is blender addon or standalone... who cares... thank you for your time again!

**Comment by dalboris** [comment]
Thanks for the feedback :)

**Comment by ebarranco** [comment]
Hi @dalboris just a word about discord. I think we need a oficial server for Vpaint and VGC too. Other open source applications use officially  Rocketchat like blender or inkscape:

https://blender.chat
https://chat.inkscape.org

And others discord like Mypaint or Lmms:

https://discord.gg/Sj2vgu
https://discord.com/invite/PruNxpG

Whatever it is, we need one.

**Comment by dalboris** [comment]
Yes, a place where to discuss VPaint/VGC and share creations is super important, I agree 200%. There used to be a VPaint forum but it got deserted. There was a gitter too but never got any traction. So I was waiting for VGC to be a bit more advanced before trying to reboot something again. But perhaps now is a good time to try a Discord :)

I'm planning to do only one Discord that would be used for both VPaint and VGC, as I don't think there is a need for two separate Discords. What do you guys think? Also, any opinion on Discord vs. Rocketchat? I was going for Discord as it seems more popular and familiar for users, but I don't have a strong opinion (I'm personally familiar with neither of them).

**Comment by ebarranco** [comment]
Yeah! just one server Vpaint/vgc it's perfect.  Discord it's great, it has audio/video channels capability, not opensource tough. Rocketchat it's open source and basic functionalities. I think my vote is for a discord server.

**Comment by dalboris** [comment]
Great, thanks for the feedback, you've been supporting the project for a long time your vote definitely counts a lot ;) I'll probably create a Discord server next week (I'm busy on some grant proposal at the moment, deadline this week).

**Comment by ebarranco** [comment]
Awesome! Meanwhile, good luck with that.

**Comment by dalboris** [comment]
I just created a Discord! Feel free to share the link: https://discord.gg/ywY4Pcv , and share your excitement about VPaint there :) Let's hope that there is some momentum. Cheers!
