### ISSUE TITLE
extract external libraries

### ISSUE THREAD

**Issue by wilhelmtell** [dalboris/vpaint#13]
It would be nice to extract external libraries from the build, or extract them within the build. This way, it would be possible to filter out compiler warnings from external libraries.

Right now I see the build is flooded with warnings, many of which come from external libraries, and are therefore not so interesting in the context of this project. When there are so many irrelevant warnings, it's too easy to miss an important warning that you can actually fix.

**Comment by seanballais** [comment]
Are you using the Terminal to compile? And what platform?

**Comment by dalboris** [comment]
Yes, I wasn't annoy by this as I'm developing on Linux, and there I only have one warning caused by Eigen. But note that Eigen is header-only, so you cannot "move it outside the build". Whatever you do, the VPaint files still need to include those Eigen *.h which are the one causing the warning. A better solution is to silent the relevant warnings in the project file, I guess.

**Comment by wilhelmtell** [comment]
I'm not sure why you only see one warning. Maybe we are compiling with a different warning level for some reason. I see something in the vicinity of 20k warnings on a clean build. That's a k there, yes, for twenty thousands.

**Comment by wilhelmtell** [comment]
Even if Eigen is header-only, you can still ignore warnings coming from there. I think msvc has pragmas for that, so something like

    #pragma warning(push)
    #  include <Eigen/Eigen>
    #pragma warning(pop)

gcc and clang won't emit warnings for system includes, so, compiling with `-isystem path/to/Eigen` and then replacing

    #include "Eigen/Eigen"

with

    #include <Eigen/Eigen>

would silent warnings from there.

I could think of a way to make this work for the three compilers, using include routing, but I don't have a windows machine to test or see if it's even necessary. So just declaring external libraries as system include paths might solve the issue.  ... which I'm the only one experiencing? Could that be?

**Comment by scribblemaniac** [comment]
> ... which I'm the only one experiencing?

You are not the only one experiencing this issue. Although I don't remember ever having quite so many warnings.

**Comment by wilhelmtell** [comment]
@dalboris if you look at the lines executing the compiler in the build's output, like

    /usr/local/bin/gcc-5 ... -o main.o main.cpp

can you find somewhere in that "`...`" part the substring `-Wall`, and, to make sure there is nowhere there the substring `-w`?

**Comment by wilhelmtell** [comment]
I've tried to extract the libraries. I don't know if you'd like what I've done. Maybe you can give me feedback.

I have a branch, [topic/rm_external_warnings](https://github.com/wilhelmtell/vpaint/tree/topic/rm_external_warnings), with one commit, 69afb6ff83a028dcb352304a134f6e3fdf0e5407. Should I submit a pull request for that..?

After extracting the libraries, I found the project builds with 4 warnings:

 * 2 warnings about re-definition of `M_PI` (why?)
 * 1 warning about an unused variable
 * 1 warning about a `bool` expression in a switch condition.

**Comment by wilhelmtell** [comment]
I'm closing this issue, because now there's pull request #16 which carries on this discussion, with (something that may or may not be) a solution already on the table.

So. See #16.

**Comment by dalboris** [comment]
Thx @wilhelmtell , let's continue the discussion on the pull request :-)

**Comment by dalboris** [comment]
Just for information (Re: compiler flags relative to warning).

I just tried a complete 64bit release build on Kubuntu 15.04, with gcc 4.9.2, Qt 5.4.2. The compile command is (here, for main.cpp, but they are all the same):

    g++ -c -pipe -std=c++11 -O2 -D_REENTRANT -Wall -W -fPIC -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../src -I. -I../../../../Qt/5.4/gcc_64/include -I../../../../Qt/5.4/gcc_64/include/QtOpenGL -I../../../../Qt/5.4/gcc_64/include/QtWidgets -I../../../../Qt/5.4/gcc_64/include/QtGui -I../../../../Qt/5.4/gcc_64/include/QtNetwork -I../../../../Qt/5.4/gcc_64/include/QtCore -I. -I../../../../Qt/5.4/gcc_64/mkspecs/linux-g++ -o main.o ../src/main.cpp

And the only warning I get is:

    In file included from ../src/VectorAnimationComplex/../Eigen/Core:256:0,
                 from ../src/VectorAnimationComplex/Eigen.h:13,
                 from ../src/VectorAnimationComplex/EdgeGeometry.h:13,
                 from ../src/VectorAnimationComplex/EdgeGeometry.cpp:8:
    ../src/VectorAnimationComplex/EdgeGeometry.cpp: In function 'void VectorAnimationComplex::{anonymous}::triangulateHelper(const QList<VectorAnimationComplex::EdgeSample>&, VectorAnimationComplex::Triangles&, bool)':
    ../src/VectorAnimationComplex/../Eigen/src/Core/util/Memory.h:643:20: warning: typedef 'VectorAnimationComplex::{anonymous}::triangulateHelper(const QList<VectorAnimationComplex::EdgeSample>&, VectorAnimationComplex::Triangles&, bool)::QuadInfo::eigen_aligned_operator_new_marker_type' locally defined but not used [-Wunused-local-typedefs]
       typedef void eigen_aligned_operator_new_marker_type;
                    ^
    ../src/VectorAnimationComplex/../Eigen/src/Core/util/Memory.h:648:41: note: in expansion of macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF'
     #define EIGEN_MAKE_ALIGNED_OPERATOR_NEW EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF(true)
                                         ^
        ../src/VectorAnimationComplex/EdgeGeometry.cpp:541:26: note: in expansion of macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW'
     struct QuadInfo    { EIGEN_MAKE_ALIGNED_OPERATOR_NEW`
