### ISSUE TITLE
C++ Codebase Standard Level

### ISSUE THREAD

**Issue by tcoyvwac** [dalboris/vpaint#131]
What is the C++ Standard level acceptable in the codebase? Assuming C++17 as VPaint is using Qt 5.12, right?

**Comment by dalboris** [comment]
Hi @tcoyvwac , sorry, I missed the notification when you initially posted this. VPaint uses C++11 only, and I'd rather not depend on later C++ standards. However, VGC, the future replacement of VPaint, uses C++17.
