### ISSUE TITLE
Adding to selection un-intuitive?

### ISSUE THREAD

**Issue by wilhelmtell** [dalboris/vpaint#17]
I find that adding to a selection is a little bit unintuitive. Unless you are familiar with the program, you might find that selecting one object, then drag-selecting another with shift, deselects the first object.

You have to make sure that when you drag-select with shift you let go of the mouse button before you let go of the shift key. If you let go of the shift key first, as I naturally just did, it won't be shift-selection but regular selection, deselecting anything that's currently selected first.

No?

**Comment by dalboris** [comment]
Hum, I'm undecided on this one, I'll have to compare with what other apps do. 

On the one hand, it might indeed be more intuitive that the SHIFT key (or other) is remembered when drag-select is initiated (this way, it doesn't matter which of SHIFT or the mouse button you release first). But on the other hand, I really like that you can interactively change the modifier keys during the drag-select, so you can always experiment and change them before release, which makes for intuitive "learning" of what they do.

Any thoughts?
