### ISSUE TITLE
class MainWindow is very big

### ISSUE THREAD

**Issue by wilhelmtell** [dalboris/vpaint#19]
I find class `MainWindow` very big. I find it handles more responsibilities than it must. If I ask myself, are there bugs in class `MainWindow`, frankly, I have very low confidence in answering either way.

What would you think of breaking it down to smaller responsibilities? So that ultimately it's easier to reason about?

Ultimately, maybe if things get small enough we can start adding test code too?

**Comment by wilhelmtell** [comment]
Umm, I've tried my hand at it a little, and extracted the undo mechanism. I hope I'm not duplicating anyone's work here?

**Comment by wilhelmtell** [comment]
To give an update, if anyone is curious: I'm running a branch on my fork, [topic/refactor_main_window](https://github.com/wilhelmtell/vpaint/tree/topic/refactor_main_window), where you can see where I'm at. It's a lot of work... I push in there as I progress, but I allow myself to force-push too. I'm just sayin'.

I strive to see `MainWindow` very small. Not much more than a screenful. But there is so much there to extract!

Along the way I've found `Global`. Sigh, another file that winks at me for refactoring. It too is so big and does so much!

**Comment by wilhelmtell** [comment]
Is it really necessary to have so much global data?

**Comment by scribblemaniac** [comment]
I hope you don't mind me asking this. It seems like you are closing all of your issues, is there a reason for this?

**Comment by wilhelmtell** [comment]
I started doubting any of this advances or adds value to the project..

**Comment by dalboris** [comment]
Hi all! Why would you think so? I'm gonna answer all this soon, I just have very limited time :-) What you did is great. Cheers, Boris.

**Comment by dalboris** [comment]
That's a lot of work you've been doing here :-) I had a quick look but I will look into more details when I have more time. Though, to give you some initial feedback, I'm a bit worried that you're a bit over-engineering here. I agree that it's big and can benefit from some refactoring, but I feel you're being slightly over-zealous, especially for such a standard class which is not very bug-prone anyway.

For instance, I personally feel that OnlineDocumentationAction was better implemented as it was before, within MainWindow. I mean, there's nothing wrong into having a big class as long as it's readable and that the responsibilities are clear. Having too many classes/files increases complexity as well, and doesn't necessary help readability or makes the code less bug-prone. The responsibility of MainWindow is to manage global actions and menus, there are just a lot of them, so it's perfectly fine to have source files with 2k+ lines, as long as it's clear and readable.

Though, I agree: currently, MainWindow does more than just managing global actions and menus (the undo mechanism was a great example!), and -those- would greatly benefit for refactoring.

What do you think?

PS: no, it's not necessary to have that much global data, and there's definitely some ugliness in there. But when you're doing research work, you often have no choice but start implementing without having a clear idea where you're going, thus using global variables makes a lot of sense for fast prototyping and get the research done. At least, every globally accessible data is contained within this Global class, which is somewhat cleaner than most research code out there ;-)
