### ISSUE TITLE
Ask to save on close

### ISSUE THREAD

**Issue by Feuermurmel** [dalboris/vpaint#23]
At least on OS X, when I create a new document or open an existing document, edit it and then close the application (by closing the main window or by choosing _VPaint_ > Quit _VPaint_), my changes are lost.

I suggest that the user is asked whether they want to save their changes to the document before it is closed.

**Comment by dalboris** [comment]
Yes, thanks for reporting this here. I am planning to implement this feature for VPaint 1.6.

**Comment by Feuermurmel** [comment]
Great! 👍

**Comment by dalboris** [comment]
Yes, it's about time, I should have implemented this years ago ;)

**Comment by Feuermurmel** [comment]
Think about how many sophisticated drawings were lost because of the lack of this prompt! :P
