### ISSUE TITLE
Associate '.vec' files with VPaint

### ISSUE THREAD

**Issue by Feuermurmel** [dalboris/vpaint#25]
At least on OS X, files created by VPaint are not associated with the VPaint application. This has multiple implications:

- Finder shows the file type as "Document", instead of a more descriptive string.
- The document cannot be opened by double clicking it.
- The document cannot be opened by dragging it to the VPaint application, either in the Finder or in the Dock.
- Duplicating a selected document in Finder does not preserve the file name extension (e.g. duplicating `test.vec` create a new file called `test.vec copy`).

**Comment by dalboris** [comment]
Thank you for this feedback! Unfortunately, I have no idea how to do that yet (I am not a Mac user). If some developer reads this and know how to implement it, I would appreciate a lot if they could do it.

Otherwise, I'll have a look myself. It is not my highest priority so it don't guarantee it will be ready for VPaint 1.6, but it would be nice, it's definitely something that should be done.

**Comment by scribblemaniac** [comment]
It should be as simple as adding this in the main `dict` of your `Info.plist`:

    <key>CFBundleDocumentTypes</key>
    <array>
        <dict>
            <key>CFBundleTypeExtensions</key>
            <array>
                <string>vec</string>
            </array>
            <key>CFBundleTypeIconFile</key>
            <string>vec.icns</string>
            <key>CFBundleTypeName</key>
            <string>VPaint File</string>
            <key>CFBundleTypeRole</key>
            <string>Editor</string>
            <key>LSTypeIsPackage</key>
            <false/>
            <key>LSIsAppleDefaultForType</key>
            <true/>
        </dict>
    </array>

`vec.icns` refers to the default icon for .vec files.

**Comment by dalboris** [comment]
Thanks! Though, there should be something to do in C++ too right, to indicate which function to call to open the file? Is the file path given as a standard argument in `argv`?

**Comment by scribblemaniac** [comment]
Ah yes, good point. I honestly don't know, but it's probably more complicated then that unfortunately because files can be dragged on an application even after it has started. Maybe they go to standard input? That's just a guess though. I'll see if I can figure it out later.

**Comment by scribblemaniac** [comment]
It took some digging, but I've figured it out. You have to override `QApplication::event` and filter for when `event->type() == QEvent::FileOpen`. From there you can handle it however you want. I rather like the way that [KeePassX](https://github.com/keepassx/keepassx/blob/master/src/gui/Application.cpp) implemented this (KeePassX is where I originally found the code to do this). As you can see, they emit a signal which is connected in the `main` function to a slot in `MainWindow` to open the file.

**Comment by dalboris** [comment]
Cool, thx for the research!

**Comment by dalboris** [comment]
Should be implemented by #39 , please reopen if not working.
