### ISSUE TITLE
Vector Logo

### ISSUE THREAD

**Issue by scribblemaniac** [dalboris/vpaint#26]
Can you please include an SVG file for the main application icon in the images folder? I would like a larger version of the icon to make the Mac .vec file icon.

**Comment by dalboris** [comment]
There is this already, I guess you missed it (or maybe you prefer a separate file with only the square icon?):

https://github.com/dalboris/vpaint/blob/master/src/Gui/images/logo.svg

**Comment by scribblemaniac** [comment]
Oops, yeah, I missed that. Thanks.
