### ISSUE TITLE
Renaming VPaint?

### ISSUE THREAD

**Issue by dalboris** [dalboris/vpaint#27]
Hi all, 

I'd like to discuss a potential issue here. About a year ago, I was brainstorming names, and I settled with "VPaint". It was short, made sense, was easy to pronounce and remember, and I checked if domain names were available (.com was empty and for sale, and .org, .net, etc... were all available), so I concluded it was unique and didn't clash with anything. 

Unfortunately:
1. I was stupid not to directly google "VPaint". There is another product called [VPaint](http://forum.unity3d.com/threads/vpaint-advanced-vertex-painting-released.192711/), a plugin for Unity to do "vertex painting". I realized this a bit late, and decided that it was a minor issue not worth changing the name, since the two were completely unrelated products.
2. More recently (a few months ago), I learned about [TVPaint](http://www.tvpaint.com/v2/content/article/home/). TVPaint is a professional 2D animation package, priced around $500 for the standard edition. I didn't try it yet, but I know some of you have. It seems to be relatively well known in the industry, but for some reason I missed it before, I guess that's what happen when you're in academia.

I am not very concerned about the first point, but I think the second is more problematic. TVPaint and VPaint are very related products, and having so similar names for related products might be confusing.

I'd like to hear your opinion on the subject. What do you think? Do you think VPaint should be renamed?

**Comment by blurymind** [comment]
We could brainstorm some names and if one that is really good pops up - consider to rename it?

**Comment by Emasoft** [comment]
I suggest this: "Velocity Paint". It is still shortening to VPaint. ;-)

**Comment by dalboris** [comment]
Yes, I guess that sounds like a good plan, maybe we'll find something good worth renaming :-) Velocity sounds pretty good in itseft, there's not even need to add "Paint" after. Of course, velocity,com, or even .org are taken (TV channel and phone company), but velocity.io is available. Let's continue to brainstorm though. Can be either based on meaningful words (paint, animation, 2D, vector, studio, toon, etc), or more abstract / not directly related as long at it sounds good, is easy to remember (e.g., Maya, Houdini, Blender), and has a good domain name available. Some idea: 2DStudio? VToon? 

By the way, name clashing with other companies are fine as long as it as nothing to do with vector graphics and animation. For instance, in this case, the fullname can indeed be "velocity paint" or "velocity animation", no legal issue, and no confusion either since products are different. But it is important that the "usage name" (i.e., what you would say in a sentence: "Have you tried Velocity, it's a damn good animation app!") has a good domain name available and does not cause confusion or clashing with a related product.

**Comment by scribblemaniac** [comment]
> velocity.io is available

You better check that again, looks to me like the name is [already registered](https://who.is/whois/velocity.io). That aside, Velocity/Velocity Paint sounds nice. There are indeed a few other things with the same name, but since none of them are animation related it isn't a huge concern.

To provide a break from the V* theme that we have going right now, I suggest  "Continuance". It conveys the time related nature of the software, it's relatively easy to remember, it's unique (I can't find anything with the same name), and there are quite a few options for domain names (continuance.org is absurdly overpriced, but .io, .net, .info, .graphics, and .software are all available and reasonable).

Of course my obligatory suggestion starting with V: "Vecform". A portmanteau of vector and transform,  it's also easy to remember, unique, and vecform.com is available along with probably every other TLD.

**Comment by blurymind** [comment]
if we could come up with a one word name like "flash" that is really easy to pronounce..
or it should be a name that is technical and explains the technology.

competitors names:
flash
toonboom
tvpaint
anime studio 
cacani

**Comment by dalboris** [comment]
Continuance is interesting but might be too long. I lean more on the short side, as blurymind suggested, something like "flash" would be great. What about blast?

**Comment by Emasoft** [comment]
Here is another suggestion, that satisfies the 4 requisites:

**VeerPaint**

1. It must comunicate the concept of movement
2. It must be a rare term, with no or few google results (to avoid being lost in the crowd)
3. It must be short and easy to memorize
4. It must not be a name already registered/trademarked

![2015-09-02 14_28_59-veerpaint logo proposal](https://cloud.githubusercontent.com/assets/713559/9631184/8ec95b80-517f-11e5-80fe-36b9b25d0300.png)

**Comment by dalboris** [comment]
Somehow, I missed that post. Anyway, let's postpone renaming VPaint for now :)
