### ISSUE TITLE
Open documentation

### ISSUE THREAD

**Issue by scribblemaniac** [dalboris/vpaint#5]
Can the documentation please be moved to gh-pages or a wiki so that people are able to add to and improve upon it. If someone decides to implement a new feature, they should be able to add that feature to the official documentation.

**Comment by dalboris** [comment]
I think a doc as a gh-pages is a great idea so people can contribute. Though, I prefer to keep also the official doc at vpaint.org/doc not be be limited by what's available by GitHub, and to make it look more integrated.

RIght now I'm busy at SIggraph, I'll try to address this issue in a few weeks.

**Comment by scribblemaniac** [comment]
Sounds good, enjoy the conference!

**Comment by dalboris** [comment]
Hi @scribblemaniac ! I created a blank wiki page for the documentation. But as I'm pretty much new to how GitHub work, can you tell me if you can edit it yourself, or if I need to do anything special? Thanks! thttps://github.com/dalboris/vpaint/wiki/Documentation

**Comment by scribblemaniac** [comment]
Yup, I am able to edit it! Thanks.

**Comment by dalboris** [comment]
Great :)
