### ISSUE TITLE
Add Key Vertex in a edge

### ISSUE THREAD

**Issue by a554b554** [dalboris/vpaint#50]
I think it's better to support add vertex in edge.

**Comment by dalboris** [comment]
Hi! I know it's not well documented yet, but you can do this with the Select tool (F1), with CTRL+click on an edge. :)

**Comment by a554b554** [comment]
Ok! thanks!

在2015-11-10 01:42:00，Chang Xiaowangliwu@zju.edu.cn写道：

Hi! I know it's not well documented yet, but you can do this with the Select tool (F1), with CTRL+click on an edge. :)
