### ISSUE TITLE
Settings not being written

### ISSUE THREAD

**Issue by scribblemaniac** [dalboris/vpaint#55]
Settings do not get written if application is quit via the menu or shortcut (tested on Mac). I have looked at this briefly and it seems that moving the code from `MainWindow::closeEvent` to a new slot and connecting it to `QApplication::aboutToQuit` will probably fix this.

**Comment by dalboris** [comment]
Oh, that's weird. It's definitely working on Linux, not sure about Widnows. Does that mean that on Mac, the about dialog gets opened at every launch, even when you uncheck "show this message at startup"?

**Comment by scribblemaniac** [comment]
Yes it does, unless people close VPaint by pressing the red X at the top of the window.

**Comment by dalboris** [comment]
Oh, I see! Thanks for noticing and reporting. Same behaviour on Linux. It seems I'm always closing with the X, or often enough that I didn't realize.
