### ISSUE TITLE
Select all should only select cells in current frame

### ISSUE THREAD

**Issue by dalboris** [dalboris/vpaint#61]
Currently, it selects all cells in the animation.

Both operations should be available, but selecting cells in current frame should be the default.

**Comment by hollunder** [comment]
Agreed. The current behavior was very surprising.
I see way more use cases for select all on current frame than select all in the entire project, so this should be easily accessible while the later could even be tucked away in some menu.

**Comment by dalboris** [comment]
This is now implemented. By default, Ctrl+A selects everything in the current frame, while Ctrl+Alt+A selects everything in the whole animation. These are also available in the "Selection" menu.

Note 1: The other specific methods "select vertices/edges/faces" don't need the two modes, since they are in fact acting as a "refinement" of the current selection. For example, to select all vertices in the current frame, you can do "Ctrl+A, S, V". Note that these methods only work for key cells, not inbetween cells (we should probably make it work for inbetween cells too, but it's a separate question).

Note 2: On KDE, Ctrl+Alt+A is already globally assigned to Shortcuts > Global Shortcuts > KWin > Activate Window Demanding Attention. I had to remove this global shortcut for Ctrl+Alt+A to work on VPaint.
