### ISSUE TITLE
XML element ordering affects behavior

### ISSUE THREAD

**Issue by scribblemaniac** [dalboris/vpaint#65]
If the vertex elements come before the edge elements in the .vec file, the vertices will be unselectable. Presumably you are just progressively rendering and the edge is being drawn over top of the vertices. Example files for testing:

Selectable vertices (expected behavior)
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Created with VPaint (http://www.vpaint.org) -->

<vec
  version="1.6">
  <playback
    framerange="0 47"
    fps="24"
    subframeinbetweening="off"
    playmode="normal"/>
  <canvas
    position="0 0"
    size="1280 720"/>
  <layer>
    <background
      color="rgba(255,255,255,1)"
      image=""
      position="0 0"
      size="cover"
      repeat="norepeat"
      opacity="1"
      hold="yes"/>
    <objects>
    <edge
        id="2"
        startvertex="0"
        endvertex="1"
        curve="xywdense(5 100,360,20 1180,360,20)"
        color="rgba(0,0,0,1)"/>
    <vertex
        id="0"
        position="100 360"
        color="rgba(0,0,0,1)"/>
      <vertex
        id="1"
        position="1180 360"
        color="rgba(0,0,0,1)"/>
    </objects>
  </layer>
</vec>
```

Unselectable vertices (unexpected behavior)
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Created with VPaint (http://www.vpaint.org) -->

<vec
  version="1.6">
  <playback
    framerange="0 47"
    fps="24"
    subframeinbetweening="off"
    playmode="normal"/>
  <canvas
    position="0 0"
    size="1280 720"/>
  <layer>
    <background
      color="rgba(255,255,255,1)"
      image=""
      position="0 0"
      size="cover"
      repeat="norepeat"
      opacity="1"
      hold="yes"/>
    <objects>
    <vertex
        id="0"
        position="100 360"
        color="rgba(0,0,0,1)"/>
      <vertex
        id="1"
        position="1180 360"
        color="rgba(0,0,0,1)"/>
      <edge
        id="2"
        startvertex="0"
        endvertex="1"
        curve="xywdense(5 100,360,20 1180,360,20)"
        color="rgba(0,0,0,1)"/>
    </objects>
  </layer>
</vec>
```

**Comment by dalboris** [comment]
Thanks for reporting this! Indeed, at least with the current version of VPaint (i.e., vertices cannot be styled and are never visible in final drawing), it seems to make sense that vertices are selectable even when they are below one or more of its incident edges.

Though: should they be selectable if they are below a wide, unrelated (non-incident) edge? (see below)

![select-vertex](https://cloud.githubusercontent.com/assets/4809739/17467553/449413be-5cd4-11e6-8411-f814d88ab26e.png)

In general, XML ordering does affect behavior, including picking behavior, and this is on purpose: XML ordering is how z-ordering is stored, and z-ordering obviously affects picking behavior, whether the picked object is a vertex, edge, or face. For instance, obviously, the relative order between two vertices affects which one should be picked. However, we may implement some special cases, but it's not very straightforward, and maybe not even desirable. Any thoughts? Note that if you create a drawing with VPaint, the end vertices of edges are always on top of the edge, unless you use one of the "alternative" raise/lower action.

In any case, one can use the topology display mode as a workaround. In this mode, probably I should always draw vertices on top of all edges.

**Comment by dalboris** [comment]
I'm closing this for now, since it is a design decision that will likely be affected by further refactoring or design decisions, hence might become obsolete. Will reopen if/when relevant
