### ISSUE TITLE
Can't open in Windows 7 32bit.

### ISSUE THREAD

**Issue by frksha** [dalboris/vpaint#66]
camera.camera pan.camera rotate.object layer panel.object move....
please ckeck tweenmaker.and make this better.
thank you

**Comment by frksha** [comment]
Hey i can't open it in my home computer.32 bit windows 7.what should i do?

**Comment by dalboris** [comment]
Thank you for the feedback! VPaint should normally work with Windows 7 32bit. Can you describe more precisely your system:

1. Exact version of Windows, which Service pack?
2. Size of RAM
3. Which graphics card

And describe more precisely the problem:

4. Did the problem occur during installation, or after installation ?
5. Any error message ?

In any case, make sure you have installed all the latest updates of Windows. In many cases, updating Windows is enough to fix the problem.

For the Camera feature, I have created a separate issue: #67

**Comment by frksha** [comment]
Win 7 proffesional.service pack 2 i think.
512 ram.On board vga.after installation.i opened v paint.that openning message appears.but after clicking ok it says vpaint has stopped working.then check online for a solution and close the program.

**Comment by dalboris** [comment]
Thank you for the info. I think that it is probably an issue with OpenGL. Your system must support OpenGL 3.2. Can you tell me which version you system support? You can do this following this:

https://blogs.esri.com/esri/supportcenter/2012/03/15/what-version-of-opengl-do-i-have-and-do-i-have-the-latest-drivers-for-my-system/

Make sure to update to the latest version of Windows, and download the latest OpenGL drivers. Unfortunately, your computer may be too old to support VPaint. For instance, 512MB or RAM is very little, I would recommend at least 4GB.

**Comment by frksha** [comment]
Thnk u boris.

**Comment by frksha** [comment]
I checked everything in my office pc.man i love this.all i need is keyframe draging and camera.oh and animatable colours.thats all i want for now.thank u boris.please let us know when will it gonna be ready

**Comment by frksha** [comment]
Timeline layers.keyframeble backgrounds.and everything that blurymind suggest was right

**Comment by frksha** [comment]
And yeah stroke matching sub option with adding sound files.

**Comment by dalboris** [comment]
I am glad that you were able to try it! Development will still be slow for one more year, but a lot of improvements should happen the year after that, starting at the beginning of 2018. I know that it is a long wait, but I hope that by the end of 2018, all of these features will be implemented. Great software takes time to create ;)

I am closing this issue now, but feel free to re-open it if you need any more help!
