### ISSUE TITLE
Scripting

### ISSUE THREAD

**Issue by SpooikypokDev** [dalboris/vpaint#73]
I saw scripting on the roadmap, and just wanted to make a suggestion: see for another language than python. Python sure can be embedded in an app, but it is quite heave, and there are better languages for this, like lua, squirrel, or scheme. I suggest that if this feature is implemented, one of the aforementioned languages be chosen. The one i would recommend for this purpose would be scheme, with guile (AGPL) or chibischeme (BSD) as an implementation.

**Comment by scribblemaniac** [comment]
Oh please not scheme! Lua might be an okay alternative, but programming in Scheme is like pulling your fingernails out with a pair of pliers.

**Comment by SpooikypokDev** [comment]
Scheme is a different paradigm, that's all. The interest of scheme, in this case, is that it's lightweight, and that it is particularly adapted to such an use, because:
1)It is a language made with lists. We can just provide a list of points to describe everything in vector, so it would be very convenient to pass such a list as an argument to the main function of a plugin.
2) it's functional, so that's you can just consider many modules as some operations on the points of an object, so every such module could receive a list of points, and return the modified list of points. Any functional language acts this way. This is good for us.
The thing that we should not do, scheme or not, is making the same mistake as gimp.
Their mistake was to think modules should only do processing and nothing else. They didn't actually extend the editor. And they couldn't. If a scripting language is ever added to VPaint, let it modify the GUI, and do such things. It would be of no use else.

**Comment by dalboris** [comment]
While I'm always happy to hear suggestions and take them into account, I'm afraid you won't be able to make me change my mind on that one: the scripting language will be python ;) Developing animation software is hard enough, there is no need to take a risky bet at some scripting language which:

1. Developers are, on average, less familiar with.
2. I have never seen used in successful animation software.

Blender is using python. Maya started using its own scripting language MEL, but is gradually transitioning in favour of python. Most animation studios that I know of are internally using python for scripting. Most of the computer graphics and computer vision community uses python for scripting. In other words, Python is a true and tested solution as a plugin language for animation software. Many people much smarter and knowledgeable than I am have been carefully weighing the pros and cons for years, as their full-time job at some of the most important companies in the field, and their conclusion was to use python. It would be quite pretentious to think we know better. 

Of course, it does not mean that python is perfect. And it does not mean that *in terms of functionality alone*, Scheme couldn't be a better choice. What it means is that there is much more than language functionality to take into account, such as: familiarity, intuitive enough syntax for non-developers, IDE support, large community, large pool of existing code, existing bindings for C++ libraries which VPaint uses.

Anyway, to answer your concern: yes, I would like the scripting/plugin architecture to support the modification of the GUI. And actually, I would argue that this is a good reason to choose python: Qt has a much better support for python than any other scripting language. :)
