### ISSUE TITLE
Face inheritance?

### ISSUE THREAD

**Issue by hollunder** [dalboris/vpaint#79]
Here is what happens:
1. Draw a large closed edge
2. Bucket fill it with some color
3. Draw a smaller closed edge within the large one
4. pull it out.
5. The smaller shape has a face with the same color as the large one.

For me that was very unexpected.
I noticed that this happens only when intersections are enabled. I assumed intersections are only about vertices and edges, not about face inheritance.
Is this intended or a bug?

**Comment by dalboris** [comment]
Ha, this is a tricky one! I agree that the behaviour is surprising in this case, but it is in in fact "intended". 

Here is what happens. When intersections are enabled, everything is intersected: not just vertices and edges, but also faces. When you draw the small closed edge at step 3, you are actually not drawing a small disk on top of the large disk. Instead, you are "cutting" the large disk into a "ring" (= large disk with a hole) and a small disk. To see that, after step 3, select the small disk (the face, not the closed edge), and delete it. You will be left with the ring only.

When you move the small closed edge out of the big one, you get the same drawing behaviour as you would with inkscape if you have a disk with a hole, and move the hole outside the external boundary (assuming you are using the "non-zero" fill rule).

Does the explanation makes sense?

**Comment by dalboris** [comment]
Another note that may be helpful in case you are familiar with Adobe Illustrator. When intersections are enabled, VPaint behaves very similarly to the "LivePaint" mode of Illustrator. When intersections are disabled, VPaint behaves more like most vector graphics editors.

**Comment by hollunder** [comment]
Thanks for the explanation.
I think that if you know that intersections intersect everything, then it can be worked with and around it.
I was not aware of that,, but I am also not familiar with how other vector graphics programs handle this case.
Maybe this is one more case where layers would simplify the situation.
