### ISSUE TITLE
Please make a script to automate compiling on MacOS X

### ISSUE THREAD

**Issue by Emasoft** [dalboris/vpaint#8]
Please make a shell script to automate compiling on MacOS X. Something like **make_vpaint.sh**.
There are many tools written in Node.js to automate the download and install of dependencies: NPM, BOWER, GRUNT, NODE-GYP, etc.

For example here is a popular open source app you can learn from:
https://git.popcorntime.io/popcorntime/desktop/tree/development

You can look at the make shell script here (this script is all you need to execute to build the app):
https://git.popcorntime.io/popcorntime/desktop/blob/development/make_popcorn.sh

For the Node.js dependencies this is the NPM configuration:
https://git.popcorntime.io/popcorntime/desktop/blob/development/package.json

This is the Grunt script:
https://git.popcorntime.io/popcorntime/desktop/blob/development/Gruntfile.js

This is the dependencies configuration for BOWER: 
https://git.popcorntime.io/popcorntime/desktop/blob/development/bower.json

This is the shell script for code signing the binary (required on MacOS X):
https://git.popcorntime.io/popcorntime/desktop/blob/development/dist/mac/codesign.sh

For installing GCC and the C++ dependencies, just take a look at the NODE-GYP examples:
https://github.com/TooTallNate/node-gyp

You can use NODE-GYP to execute the the QT Mac deployment tool that can be found in the *QTDIR/bin/macdeployqt* folder.
http://doc.qt.io/qt-4.8/deployment-mac.html#macdeploy

You can also use those tools for automate the build on all the other OS platforms, like this app does.

**Comment by scribblemaniac** [comment]
I would much rather have a build script for homebrew. I doubt that either will ever happen though, because it will be difficult to locate the correct version of qt and gcc (not confusing it with qt 4 or the version of gcc that comes with mac) and to create the custom mspec. If you just want a simple installation, download the stable release binary. If you really need the latest version, there are very detailed instructions on how to build it with qt creator on the homepage.

**Comment by dalboris** [comment]
I take good note of this, but indeed, I'll probably not spend time on this as it is not critical and I have a thousands other things to do. That being said, I do appreciate input regarding MacOS, I've I'm really new to this and I'm happy to learn best practices. Making the MacOS binary for VPaint was pretty much my only experience using a mac (I'm 95% of the time on Linux, 5% on Windows).
