### ISSUE TITLE
Autosave / Crash recovery

### ISSUE THREAD

**Issue by hollunder** [dalboris/vpaint#85]
Since I just had my first proper crash and data loss I wish there was some way to recover from that without losing everything.
Autosave would be one simple way, but maybe not ideal.
Better would be some sort of delta save, which could at the same time serve as undo/redo and would allow reproducing certain situations.
I've seen this in this program and found it to be a great idea: http://non.tuxfamily.org/wiki/Non%20Timeline

**Comment by dalboris** [comment]
I feel really bad about not answering this at the time, a thousand times sorry.

There actually is an autosave feature, although not documented and you probably didn't know where to look for. VPaint autosaves every minute to [`QStandardPaths::DataLocation`](https://doc.qt.io/qt-5/qstandardpaths.html), which is something that looks like the following depending on your system:

```
~/.local/share/VPaint/VPaint/autosave
~/Library/Application Support/VPaint/autosave
C:/Users/<USER>/AppData/Local/VPaint/autosave
C:/ProgramData/VPaint/autosave
```

I am closing this but will try to make sure to at least add it to the documentation #77.
