### ISSUE TITLE
Is this project dead? Almost one year passed since the last update.

### ISSUE THREAD

**Issue by Emasoft** [dalboris/vpaint#89]
Is this project dead? Almost one year passed since the last update.

**Comment by dalboris** [comment]
Hi @Emasoft, thx for stopping by! I am currently a postdoctoral researcher at Pixar, which leaves me little time for VPaint. My position ends at the end of September, and starting October 2017, I'll start working full-time on this project. I'll make an announcement when I have a more concrete plan.

**Comment by buckle2000** [comment]
Thank you for your work!
