### ISSUE TITLE
Change the About page text + link to vgc

### ISSUE THREAD

**Issue by dalboris** [dalboris/vpaint#90]
The "about" text in VPaint 1.6 is quit out of date. I should update it and include a link to vgc.io, Patreon, etc. I should also migrate the mailing list to be a VGC mailing list, and prompt users to sign up to that one.

**Comment by algorev** [comment]
Good idea.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by dalboris** [comment]
Implemented by:

https://github.com/dalboris/vpaint/commit/696ba2ecee67f5e7086b32c18cdb15425b0bbe83
https://github.com/dalboris/vpaint/commit/a202d2bf6f5c413f44ad4cbba48628a4c3029656
